#!/usr/bin/env python3
"""Erhobene Marktdaten Hannover, Stand 17.08.2026.

Quellen je Feld:
  gemessen  = eigener Live-Crawl (Quelltext, Header, Sitemap)
  Website   = auf der Anbieterseite gelesener Preis
  Snippet   = aus Suchergebnis-Auszug, nicht auf der Seite verifiziert
"""

# --- Anbieter -------------------------------------------------------------
# farben: aus theme-color, CSS-Marken-Variablen und Komponenten-Regeln gezogen;
#         Bootstrap- und WordPress-Standardpaletten wurden ausgeschlossen.
ANBIETER = [
 dict(dom="tanzschule-bothe.de", name="Tanzschulen Familie Bothe", kurz="Familie Bothe",
      seg="Tanzschule", ort="Hannover ×3 + Burgwedel", wir=True,
      farben=["#9BBE00", "#D8063A"], farbquelle="eigenes CI (assets/style.css)",
      gegruendet=1954, seiten=391, ttfb=0.90, kb=327, desc=748, h1=8, h2=0, ld=0, og=0, webp=0,
      staerke="Größtes Angebot der Region: 3 Häuser, 11 Säle, rund 220 Angebote pro Woche.",
      schwaeche="Technisch das Schlusslicht im Feld. Keine einzige Landingpage pro Tanzstil.",
      stile=["Standard", "Latein", "Discofox", "Salsa", "Bachata", "Tango", "Swing",
             "Hip Hop", "Contemporary", "Ballett", "Breakdance", "Kindertanz",
             "Linedance", "Hochzeit", "Privatstunde", "Welttanzprogramm", "Medaillen"],
      preise=[("Worlddancing Complete", 61.00, "10 Raten, 30 UE", "Website"),
              ("Worlddancing Flex", 71.00, "flexibel nach 5 Monaten", "Website"),
              ("VIP-Jugendclub", 55.00, "6 Monate Mindestlaufzeit, 32 UE/Jahr", "Website")],
      voll=61.00, voll_label="Worlddancing Complete", bindung="10 Raten"),

 dict(dom="bothe.de", name="Tanzschule Susanne Bothe", kurz="Susanne Bothe",
      seg="Tanzschule", ort="Hannover", wir=False,
      farben=["#005262", "#ed3e47", "#8cad2d"], farbquelle="CSS-Variablen, Komponenten",
      gegruendet=1993, seiten=40, ttfb=1.96, kb=93, desc=155, h1=1, h2=3, ld=0, og=6, webp=0,
      staerke="12 Kurs-Landingpages im sauberen Silo. Rankt für die Stil-Suchbegriffe. Baut bis 2027 das Bothe Loft mit 1.600 m².",
      schwaeche="Langsam (TYPO3), kein strukturiertes Datenformat.",
      stile=["Standard", "Latein", "Discofox", "Salsa", "West Coast Swing", "Hip Hop",
             "Contemporary", "Kindertanz", "Hochzeit", "Privatstunde", "Welttanzprogramm"],
      preise=[], voll=None, voll_label="nicht veröffentlicht", bindung="—"),

 dict(dom="tanzschulemeiners.de", name="ADTV Tanzschule Meiners", kurz="Meiners",
      seg="Tanzschule", ort="Hannover Mitte", wir=False,
      farben=["#20b038", "#7a00df"], farbquelle="CSS-Variablen",
      gegruendet=1980, seiten=3, ttfb=2.32, kb=129, desc=289, h1=1, h2=2, ld=1, og=6, webp=0,
      staerke="Bestes technisches Fundament im Feld. Weltklasse-Historie, Medienpartner ARD/NDR/RTL.",
      schwaeche="Nur 3 Seiten insgesamt — kaum Inhaltstiefe. Teuerster Anbieter.",
      stile=["Standard", "Latein", "Discofox", "Salsa", "Tango", "Rumba", "Samba",
             "Jive", "Cha-Cha", "Foxtrott", "Hochzeit", "Medaillen", "Privatstunde"],
      preise=[("Flatrate", 90.00, "kürzeste Laufzeit; 85 € / 80 € bei längerer", "Website"),
              ("Einmal pro Woche", 70.00, "12 Monate; 65 € / 60 € gestaffelt", "Website"),
              ("Kurssystem 3×60 Min", 90.00, "Einzelkurs", "Website"),
              ("Kurssystem 8×60 Min", 160.00, "Einzelkurs", "Website"),
              ("Privatstunde 60 Min", 100.00, "einzeln", "Website")],
      voll=90.00, voll_label="Flatrate", bindung="12 Monate gestaffelt"),

 dict(dom="tanzschule-feeling.de", name="Tanzschule Feeling", kurz="Feeling",
      seg="Tanzschule", ort="Hannover", wir=False,
      farben=["#00acad", "#91bd09", "#e62727"], farbquelle="CSS-Variablen, Komponenten",
      gegruendet=2010, seiten=0, ttfb=1.81, kb=186, desc=137, h1=1, h2=2, ld=1, og=13, webp=0,
      staerke="Sauber gebaut, 13 Open-Graph-Tags — die stärkste Social-Vorbereitung im Feld.",
      schwaeche="Keine auffindbare Sitemap, dadurch schwer indexierbar.",
      stile=["Standard", "Latein", "Discofox", "Salsa", "Tango", "Rumba", "Samba",
             "Jive", "Cha-Cha", "Hip Hop", "Kindertanz", "Hochzeit", "Privatstunde"],
      preise=[], voll=None, voll_label="nicht veröffentlicht", bindung="—"),

 dict(dom="happyhours.de", name="Happy Hours Tanzschule & Events", kurz="Happy Hours",
      seg="Preisführer", ort="Hannover", wir=False,
      farben=["#ff6600", "#7f54b3"], farbquelle="CSS-Variablen, Komponenten",
      gegruendet=1993, seiten=98, ttfb=2.62, kb=89, desc=0, h1=0, h2=9, ld=0, og=0, webp=0,
      staerke="Besetzt Discofox mit drei eigenen Adressen. 25 Discofox-Kurse über vier Level. Klarster Preisvorteil.",
      schwaeche="Technisch die schwächste Seite im Test — keine Beschreibung, keine H1, kein Schema.",
      stile=["Discofox", "Standard", "Latein", "Salsa", "Bachata", "Merengue",
             "Linedance", "Zumba", "Hip Hop", "Hochzeit", "Rumba", "Samba", "Jive"],
      preise=[("Basis-Tarif", 29.90, "feste Gruppe ohne Tausch, 90 Tage Kündigung", "Website"),
              ("Comfort-Tarif", 34.90, "wöchentliches Training, 90 Tage Kündigung", "Website"),
              ("Paar-Tanzclub", 39.90, "Gruppe, 90 Tage Kündigung", "Website"),
              ("Paar-Tanzclub kurz", 44.90, "30 Tage Kündigung", "Website"),
              ("10er-Karte", 109.00, "Happy-Card, unbefristet", "Website"),
              ("Probestunde", 10.00, "einmalig", "Website")],
      voll=44.90, voll_label="Paar-Tanzclub (30 Tage)", bindung="30–90 Tage Kündigung"),

 dict(dom="moveandstyle.de", name="Move & Style Dance Academy", kurz="Move & Style",
      seg="Urban", ort="Hannover", wir=False,
      farben=["#ff8500", "#9bc53d"], farbquelle="Komponenten",
      gegruendet=2008, seiten=0, ttfb=2.62, kb=76, desc=156, h1=5, h2=0, ld=1, og=0, webp=0,
      staerke="Nennt sich im Seitentitel offensiv “Die beste Tanzschule in Hannover”. Breitestes Urban-Programm.",
      schwaeche="52 Wochen Mindestlaufzeit bei allen Tarifen. Keine Sitemap.",
      stile=["Hip Hop", "Breakdance", "Dancehall", "Twerk", "Burlesque", "Ballett",
             "Jazz", "Contemporary", "Modern", "Zumba", "Pilates", "Kindertanz",
             "Salsa", "Hochzeit"],
      preise=[("Single — 1 Kurs/Woche", 43.33, "10,00 €/Woche, 52 Wochen", "Website"),
              ("Basic — 2 Kurse/Woche", 54.12, "12,49 €/Woche, 52 Wochen", "Website"),
              ("Standard — 3 Kurse/Woche", 64.96, "14,99 €/Woche, 52 Wochen", "Website"),
              ("Unlimited", 71.46, "16,49 €/Woche, 52 Wochen", "Website")],
      voll=71.46, voll_label="Unlimited", bindung="52 Wochen"),

 dict(dom="salsa-del-alma.de", name="Salsa del Alma", kurz="Salsa del Alma",
      seg="Spezialist", ort="Hannover", wir=False,
      farben=["#b20000", "#f36e18"], farbquelle="CSS-Variablen, Komponenten",
      gegruendet=2005, seiten=42, ttfb=1.19, kb=118, desc=110, h1=5, h2=1, ld=2, og=10, webp=0,
      staerke="Eigene Landingpages für Hochzeitstanz und Hip Hop. Weltmeister als Hip-Hop-Trainer.",
      schwaeche="Sehr langsame Antwortzeit gemessen (7,98 s im ersten Durchlauf).",
      stile=["Salsa", "Bachata", "Kizomba", "Merengue", "Hip Hop", "Hochzeit"],
      preise=[("Flatrate", 73.50, "68–79 € je nach Laufzeit", "Snippet")],
      voll=73.50, voll_label="Flatrate (Mittelwert)", bindung="laufzeitabhängig"),

 dict(dom="ttc-gelb-weiss.de", name="TTC Gelb-Weiss Hannover", kurz="TTC Gelb-Weiss",
      seg="Verein", ort="Hannover", wir=False,
      farben=["#d97706", "#004f9e"], farbquelle="Grundzählung",
      gegruendet=1958, seiten=693, ttfb=0.67, kb=88, desc=152, h1=1, h2=7, ld=1, og=6, webp=6,
      staerke="Mit Abstand günstigster Anbieter. 693 Seiten, schnellste Antwortzeit im Feld.",
      schwaeche="Vereinsstruktur, Turnierfokus — kein Breitenangebot für Einsteiger.",
      stile=["Standard", "Latein", "Discofox", "West Coast Swing", "Turniertanz"],
      preise=[("Mitgliedschaft Paare", 15.50, "pro Monat, Standard/Latein", "Website"),
              ("Turniertraining", 18.00, "pro Monat", "Website"),
              ("Discofox-Kurs", 40.00, "pro Kurs, 4 Einheiten", "Website"),
              ("Einsteigerkurs", 55.00, "pro Kurs; als Mitglied ab 15,50 €", "Website")],
      voll=15.50, voll_label="Mitgliedschaft", bindung="Vereinsmitgliedschaft"),

 dict(dom="physicalpark.de", name="Physicalpark", kurz="Physicalpark",
      seg="Urban", ort="Hannover", wir=False,
      farben=["#d7b398", "#f44236"], farbquelle="CSS-Variablen, Komponenten",
      gegruendet=2010, seiten=497, ttfb=1.05, kb=0, desc=0, h1=0, h2=0, ld=0, og=0, webp=0,
      staerke="Kindertanz für 9,90 € pro Woche, monatlich kündbar. Rankt für Kindertanz Hannover.",
      schwaeche="Fitnessstudio mit Tanzangebot, keine Tanzschule im engeren Sinn.",
      stile=["Kindertanz", "Hip Hop", "Zumba", "Pilates", "Yoga"],
      preise=[("Kindermitgliedschaft", 42.90, "9,90 €/Woche, monatlich kündbar", "Website")],
      voll=42.90, voll_label="Kindermitgliedschaft", bindung="monatlich kündbar"),

 dict(dom="dafunk.dance", name="Da Funk Streetdance", kurz="Da Funk",
      seg="Urban", ort="Hannover", wir=False,
      farben=["#f100ff", "#12c9e4"], farbquelle="theme-color",
      gegruendet=2015, seiten=0, ttfb=0.71, kb=51, desc=106, h1=1, h2=0, ld=1, og=4, webp=0,
      staerke="Reiner Streetdance-Spezialist, 30 Kurse. Klare, moderne Preisseite mit Abo-Modell.",
      schwaeche="Schmales Programm, kein Paartanz.",
      stile=["Hip Hop", "Streetdance", "Breakdance", "Dancehall", "Jazz", "Modern"],
      preise=[("Probestunde", 9.00, "einmalig", "Website"),
              ("Anmeldegebühr", 29.00, "einmalig", "Website")],
      voll=None, voll_label="Abo-Preis nicht ausgelesen", bindung="Abo"),

 dict(dom="move-dance.de", name="Move & Dance", kurz="Move & Dance",
      seg="Tanzschule", ort="Hannover Kabelkamp", wir=False,
      farben=["#782842", "#f4a261"], farbquelle="CSS-Variablen, Komponenten",
      gegruendet=2011, seiten=1, ttfb=0.72, kb=40, desc=95, h1=3, h2=3, ld=0, og=0, webp=0,
      staerke="Schlankeste Seite im Feld (40 kB). Eigene Bar am Standort.",
      schwaeche="Nur 185 sichtbare Wörter auf der Startseite, eine Seite in der Sitemap.",
      stile=["Standard", "Latein", "Discofox", "Zumba", "Pilates", "Tai Chi",
             "Kindertanz", "Linedance"],
      preise=[], voll=None, voll_label="nicht veröffentlicht", bindung="—"),

 dict(dom="kressler.de", name="Tanzschule Kressler", kurz="Kressler",
      seg="Tanzschule", ort="Garbsen, Neustadt, Gehrden", wir=False,
      farben=["#398439", "#d58512"], farbquelle="CSS-Variablen, Komponenten",
      gegruendet=1985, seiten=410, ttfb=2.05, kb=194, desc=0, h1=1, h2=0, ld=0, og=4, webp=0,
      staerke="410 Seiten, breitestes Stilangebot im Umland, sehr aktives Eventprogramm.",
      schwaeche="Keine Meta-Beschreibung, Startseite heißt schlicht “Startseite”.",
      stile=["Standard", "Latein", "Discofox", "Salsa", "Bachata", "Boogie",
             "Hip Hop", "Breakdance", "Contemporary", "Linedance", "Hochzeit",
             "Kindertanz", "Rumba", "Cha-Cha", "Foxtrott"],
      preise=[("Party-Tickets", 12.00, "Events 5–30 €, keine Kurspreise veröffentlicht", "Website")],
      voll=None, voll_label="nicht veröffentlicht", bindung="—"),

 dict(dom="tanzsport-phoenix.de", name="TSC Phoenix Hannover", kurz="TSC Phoenix",
      seg="Verein", ort="Hannover", wir=False,
      farben=["#003399", "#c4ebf1"], farbquelle="Grundzählung",
      gegruendet=1974, seiten=39, ttfb=0.77, kb=59, desc=0, h1=2, h2=0, ld=0, og=3, webp=0,
      staerke="Vereinsbeiträge deutlich unter Tanzschulniveau. Discofox für Erwachsene.",
      schwaeche="Keine Meta-Beschreibung, kein Schema, schwache Auffindbarkeit.",
      stile=["Standard", "Latein", "Discofox", "Kindertanz", "Ballett", "Linedance"],
      preise=[], voll=None, voll_label="nicht veröffentlicht", bindung="—"),

 dict(dom="tanzschule-graeper.de", name="ADTV Tanzschule Bernd Gräper", kurz="Gräper",
      seg="Tanzschule", ort="Langenhagen", wir=False,
      farben=["#ff4040", "#0f2ccf"], farbquelle="Komponenten",
      gegruendet=1990, seiten=15, ttfb=0.56, kb=509, desc=166, h1=0, h2=5, ld=2, og=5, webp=30,
      staerke="Einziger im Feld mit durchgängigen WebP-Bildern. Schnellste Auslieferung.",
      schwaeche="509 kB Seitengewicht, keine einzige H1-Überschrift.",
      stile=["Standard", "Latein", "Discofox", "Kindertanz", "Hochzeit", "Linedance"],
      preise=[], voll=None, voll_label="nicht veröffentlicht", bindung="—"),

 dict(dom="jegella.de", name="Tanzschule Jegella", kurz="Jegella",
      seg="Tanzschule", ort="Lehrte", wir=False,
      farben=["#961643", "#f4a261"], farbquelle="CSS-Variablen, Komponenten",
      gegruendet=1995, seiten=1, ttfb=0.85, kb=81, desc=89, h1=6, h2=13, ld=0, og=0, webp=0,
      staerke="Eventlocation im Rathaus Lehrte, breites Nebenangebot.",
      schwaeche="Seitentitel ist nur “jegella.de” — 10 Zeichen, ohne Ort und Leistung.",
      stile=["Standard", "Latein", "Discofox", "Hip Hop", "Linedance",
             "Kindertanz", "Hochzeit", "Privatstunde"],
      preise=[], voll=None, voll_label="nicht veröffentlicht", bindung="—"),

 dict(dom="u-dance.de", name="Tanzschule UDance", kurz="U-Dance",
      seg="Spezialist", ort="Hannover", wir=False,
      farben=["#c2185b", "#00838f"], farbquelle="nicht erreichbar — Farben geschätzt",
      gegruendet=2012, seiten=None, ttfb=None, kb=None, desc=None, h1=None, h2=None,
      ld=None, og=None, webp=None,
      staerke="Eigene Preisseite, klarer Latin-Fokus.",
      schwaeche="Website war während der gesamten Erhebung nicht erreichbar.",
      stile=["Salsa", "Bachata", "Kizomba"],
      preise=[], voll=None, voll_label="nicht abrufbar", bindung="—"),
]

# --- Sichtbarkeitstest ----------------------------------------------------
# Geprüft wurde, welche Anbieter zu diesen Suchanfragen mit einer Seite erscheinen.
# Das ist eine Anwesenheitsprüfung, kein Positions-Tracking.
SICHTBARKEIT = [
 dict(q="Tanzkurs Hannover", note="Der Haupt-Suchbegriff", status="teil",
      wir="erscheint mit /paartanz/ — der Sammelseite ohne Beschreibung",
      andere=["citysports.de", "Tanzschule Feeling", "Happy Hours", "bothe.de",
              "Meiners", "Kressler", "Move & Dance", "Move & Style"]),
 dict(q="Hochzeitstanz Hannover", note="Höchster Kundenwert", status="nein",
      wir="kein Treffer",
      andere=["citysports.de", "heiraten.de", "Salsa del Alma (eigene Seite)",
              "Move & Style (eigene Seite)", "Meiners", "myweddingdance.eu",
              "hochzeit-feiern-in-hannover.de"]),
 dict(q="Discofox Hannover", note="Meistgetanzter Paartanz", status="nein",
      wir="kein Treffer trotz eigenem Discofox-Angebot",
      andere=["Happy Hours (3 Adressen)", "bothe.de (eigene Seite)",
              "TTC Gelb-Weiss", "TSC Phoenix", "ts-teichert.de", "myheimat.de"]),
 dict(q="Kindertanz Hannover", note="Eltern entscheiden mobil", status="falsch",
      wir="erscheint mit /bwkids/ — Titel lautet “Tanzangebot Erwachsene Paartanz”",
      andere=["bothe.de (2 eigene Seiten)", "Musikschule der Stadt",
              "Physicalpark", "vuvivi.de"]),
 dict(q="Hip Hop Hannover", note="Zielgruppe Studio B", status="nein",
      wir="kein Treffer",
      andere=["citysports.de (4 Stadtteil-Adressen)", "Salsa del Alma (eigene Seite)",
              "dafunk.dance", "Stadtteilzentren", "Move & Style"]),
 dict(q="Schülertanzkurs Hannover", note="Kerngeschäft Jugendliche", status="ja",
      wir="erscheint mit /schuelertanzkurse/ — die einzige gut aufgestellte Kursseite",
      andere=["bothe.de", "Kressler", "ts-teichert.de", "tanzkurs.com",
              "Musikschule der Stadt"]),
 dict(q="Tanzschule Hannover Preise", note="Kaufabsicht, kurz vor Abschluss", status="nein",
      wir="kein Treffer — auf der Website steht kein Preis",
      andere=["superprof.de", "U-Dance (eigene Preisseite)", "Move & Style (eigene Preisseite)",
              "bothe.de", "Salsa del Alma"]),
]

# --- Portale --------------------------------------------------------------
PORTALE = [
 ("citysports.de", "Sportkurs-Verzeichnis", "Erscheint bei Tanzkurs, Hochzeitstanz und Hip Hop — für Hip Hop mit vier eigenen Stadtteil-Adressen."),
 ("heiraten.de", "Hochzeitsportal", "Besetzt Hochzeitstanz Hannover mit einer reinen Anbieterliste."),
 ("tanzkurs.com", "Tanzschul-Verzeichnis", "Erscheint bei Tanzschule Hannover und Schülertanzkurs."),
 ("myweddingdance.eu", "Tanzlehrer-Vermittlung", "Vermittelt Privatlehrer für Hochzeitstanz und greift damit direkt Marge ab."),
 ("vuvivi.de", "Freizeitportal Familien", "Erscheint bei Kindertanz Hannover."),
 ("superprof.de", "Nachhilfe-/Kursplattform", "Erscheint bei Preissuchen und nennt Durchschnittspreise für Hannover."),
]
